# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09b609340067544bdf8af2d44bab37b2db02663232e5cdc24f754ab238902775e7b96f619a415d00305d9c54098d93ca3e0a2575d8a73221ebfd3168829e2ba6

test:
  secret_key_base: 91e7368a6335287e0e6d67e14bc67752c6f086aa742ad75dc1684390f0632df1f22a0cd1f4def3308d9dc3975f45a9033f9c3988e6692d3a18e2fa8888075659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
